services:
  postgres:
    image: postgres:15-alpine
    container_name: chatapp-postgres
    environment:
      POSTGRES_DB: chatappdb_dev
      POSTGRES_USER: chatapp_user
      POSTGRES_PASSWORD: dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatapp_user -d chatappdb_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chatapp-network

  redis:
    image: redis:7-alpine
    container_name: chatapp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chatapp-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: chatapp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@chatapp.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - chatapp-network

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  chatapp-network:
    driver: bridge